version: '3'

services:
  web:
    build: .
    command: gunicorn ToDoApp.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - .:/ToDoApp
    ports:
        - "8000:8000"
    environment:
      - SECRET_KEY = please_change_me