# Generated by Django 2.1.7 on 2019-04-10 19:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, help_text='Explain your task!')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 4, 10, 19, 27, 28, 516403, tzinfo=utc))),
                ('due_date', models.DateTimeField(default=datetime.datetime(2019, 4, 10, 19, 27, 28, 516431, tzinfo=utc))),
                ('completed', models.BooleanField(default=False)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
