# Generated by Django 2.1.7 on 2019-04-19 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 19, 11, 23, 9, 297427, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 19, 11, 23, 9, 297467, tzinfo=utc)),
        ),
    ]
