# Generated by Django 2.1.7 on 2019-04-19 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0002_auto_20190419_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 19, 11, 23, 50, 397174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 19, 11, 23, 50, 397199, tzinfo=utc)),
        ),
    ]
