# Generated by Django 2.1.7 on 2019-04-19 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0003_auto_20190419_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 11, 32, 17, 825079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 11, 32, 17, 825105, tzinfo=utc)),
        ),
    ]
