# Generated by Django 2.1.7 on 2019-04-19 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0004_auto_20190419_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 4, 19)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default=datetime.date(2019, 4, 19)),
        ),
    ]
