# Generated by Django 2.1.7 on 2019-04-19 11:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TaskList', '0005_auto_20190419_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 11, 39, 38, 590109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 19, 11, 39, 38, 590135, tzinfo=utc)),
        ),
    ]
